export const TYPE_TXN_HISTORY = {
  CRYPTO: 'CRYPTO',
  FIAT: 'FIAT',
  CARD: 'CARD',
  CASHBACK: 'CASHBACK',
  STAKING: 'STAKING',
  OTC: 'OTC',
  BIZ: 'BIZ',
}

export const TITLE_TXN_HISTORY_NEW = {
  DEPOSIT: 'Deposit',
  WITHDRAWAL: 'Withdrawal',
  EXCHANGE: 'Exchange',
  EARNING_REWARD: 'Earning Reward',
  EARNING_CLAIMED: 'Earning Claimed',
  CASHBACK: 'Cashback',
  TOP_UP: 'Top Up',
  CAMPAIGN_REWARD: 'Campaign Reward',
  REFERRAL_BONUS: 'Referral Bonus',
  STAKE_ALLOCATION: 'Stake Allocation',
  REFUND_CLAIM: 'Refund Claim',
  TOKEN_CLAIM: 'Token Claim',
  REWARD: 'Reward',
  // Новые элементы:
  SUPERCHARGE_STAKED: 'Supercharge Staked',
  SUPERCHARGE_CLAIMED: 'Supercharge Claimed',
  STAKING_REWARD: 'Staking Reward',
  FI_STAKED: 'FI Staked',
  FI_CLAIMED: 'FI Claimed',
  // TODO change Pairs ??
  FIDEUM_EARN_STAKED: 'Fideum Earn Staked',
  FIDEUM_EARN_CLAIMED: 'Fideum Earn Claimed',
}

export const GREEN_TEXT_STYLES = [
  TITLE_TXN_HISTORY_NEW.EARNING_REWARD,
  TITLE_TXN_HISTORY_NEW.DEPOSIT,
  TITLE_TXN_HISTORY_NEW.TOP_UP,
  TITLE_TXN_HISTORY_NEW.CASHBACK,
  TITLE_TXN_HISTORY_NEW.REFUND_CLAIM,
  TITLE_TXN_HISTORY_NEW.TOKEN_CLAIM,
  TITLE_TXN_HISTORY_NEW.STAKING_REWARD,
  TITLE_TXN_HISTORY_NEW.SUPERCHARGE_CLAIMED,
  TITLE_TXN_HISTORY_NEW.FI_CLAIMED,
  TITLE_TXN_HISTORY_NEW.FIDEUM_EARN_CLAIMED,
]

export const PLUS_SIGN_TITLES = [
  TITLE_TXN_HISTORY_NEW.EARNING_REWARD,
  TITLE_TXN_HISTORY_NEW.EARNING_CLAIMED,
  TITLE_TXN_HISTORY_NEW.CASHBACK,
  TITLE_TXN_HISTORY_NEW.CAMPAIGN_REWARD,
  TITLE_TXN_HISTORY_NEW.DEPOSIT,
  TITLE_TXN_HISTORY_NEW.TOP_UP,
  TITLE_TXN_HISTORY_NEW.REFERRAL_BONUS,
  TITLE_TXN_HISTORY_NEW.REFUND_CLAIM,
  TITLE_TXN_HISTORY_NEW.TOKEN_CLAIM,
  TITLE_TXN_HISTORY_NEW.EXCHANGE,
  TITLE_TXN_HISTORY_NEW.TOKEN_CLAIM,
  TITLE_TXN_HISTORY_NEW.REFUND_CLAIM,
  TITLE_TXN_HISTORY_NEW.SUPERCHARGE_CLAIMED,
  TITLE_TXN_HISTORY_NEW.FI_CLAIMED,
  TITLE_TXN_HISTORY_NEW.FIDEUM_EARN_CLAIMED,
  TITLE_TXN_HISTORY_NEW.STAKING_REWARD,
]
export const MINUS_SIGN_TITLES = [
  TITLE_TXN_HISTORY_NEW.WITHDRAWAL,
  TITLE_TXN_HISTORY_NEW.STAKE_ALLOCATION,
  TITLE_TXN_HISTORY_NEW.SUPERCHARGE_STAKED,
  TITLE_TXN_HISTORY_NEW.FI_STAKED,
  TITLE_TXN_HISTORY_NEW.FIDEUM_EARN_STAKED,
]
