export type Country = {
  name: string
  flag: string
  phoneCode: string
}

type Countries = {
  [key: string]: Country
}

export const countriesData: Countries = {
  AND: { name: 'Andorra', flag: '🇦🇩', phoneCode: '+376' },
  ARG: { name: 'Argentina', flag: '🇦🇷', phoneCode: '+54' },
  ALB: { name: 'Albania', flag: '🇦🇱', phoneCode: '+355' },
  AUS: { name: 'Australia', flag: '🇦🇺', phoneCode: '+61' },
  ARM: { name: 'Armenia', flag: '🇦🇲', phoneCode: '+374' },
  ATG: { name: 'Antigua and Barbuda', flag: '🇦🇬', phoneCode: '+1268' },
  AZE: { name: 'Azerbaijan', flag: '🇦🇿', phoneCode: '+994' },
  ECU: { name: 'Ecuador', flag: '🇪🇨', phoneCode: '+593' },
  CHL: { name: 'Chile', flag: '🇨🇱', phoneCode: '+56' },
  IMN: { name: 'Isle of Man', flag: '🇮🇲', phoneCode: '+44' },
  AUT: { name: 'Austria', flag: '🇦🇹', phoneCode: '+43' },
  BEN: { name: 'Benin', flag: '🇧🇯', phoneCode: '+229' },
  BIH: { name: 'Bosnia and Herzegovina', flag: '🇧🇦', phoneCode: '+387' },
  BHS: { name: 'Bahamas', flag: '🇧🇸', phoneCode: '+1242' },
  BRN: { name: 'Brunei', flag: '🇧🇳', phoneCode: '+673' },
  BLR: { name: 'Belarus', flag: '🇧🇾', phoneCode: '+375' },
  BEL: { name: 'Belgium', flag: '🇧🇪', phoneCode: '+32' },
  BOL: { name: 'Bolivia', flag: '🇧🇴', phoneCode: '+591' },
  BGD: { name: 'Bangladesh', flag: '🇧🇩', phoneCode: '+880' },
  BWA: { name: 'Botswana', flag: '🇧🇼', phoneCode: '+267' },
  BRA: { name: 'Brazil', flag: '🇧🇷', phoneCode: '+55' },
  BLZ: { name: 'Belize', flag: '🇧🇿', phoneCode: '+501' },
  CAN: { name: 'Canada', flag: '🇨🇦', phoneCode: '+1' },
  BRB: { name: 'Barbados', flag: '🇧🇧', phoneCode: '+1246' },
  BTN: { name: 'Bhutan', flag: '🇧🇹', phoneCode: '+975' },
  BFA: { name: 'Burkina Faso', flag: '🇧🇫', phoneCode: '+226' },
  CCK: { name: 'Cocos (Keeling) Islands', flag: '🇨🇨', phoneCode: '+61' },
  KHM: { name: 'Cambodia', flag: '🇰🇭', phoneCode: '+855' },
  EGY: { name: 'Egypt', flag: '🇪🇬', phoneCode: '+20' },
  CHN: { name: 'China', flag: '🇨🇳', phoneCode: '+86' },
  ERI: { name: 'Eritrea', flag: '🇪🇷', phoneCode: '+291' },
  CAR: { name: 'Central African Republic', flag: '🇨🇫', phoneCode: '+236' },
  XXK: { name: 'Kosovo', flag: '🇽🇰', phoneCode: '+383' },
  CIV: { name: "Côte d'Ivoire", flag: '🇨🇮', phoneCode: '+225' },
  ETH: { name: 'Ethiopia', flag: '🇪🇹', phoneCode: '+251' },
  MAR: { name: 'Morocco', flag: '🇲🇦', phoneCode: '+212' },
  FJI: { name: 'Fiji', flag: '🇫🇯', phoneCode: '+679' },
  FRO: { name: 'Faroe Islands', flag: '🇫🇴', phoneCode: '+298' },
  FSM: { name: 'Micronesia', flag: '🇫🇲', phoneCode: '+691' },
  GEO: { name: 'Georgia', flag: '🇬🇪', phoneCode: '+995' },
  HRV: { name: 'Croatia', flag: '🇭🇷', phoneCode: '+385' },
  GGY: { name: 'Guernsey', flag: '🇬🇬', phoneCode: '+44' },
  GHA: { name: 'Ghana', flag: '🇬🇭', phoneCode: '+233' },
  CYP: { name: 'Cyprus', flag: '🇨🇾', phoneCode: '+357' },
  CZE: { name: 'Czech Republic', flag: '🇨🇿', phoneCode: '+420' },
  GIN: { name: 'Guinea', flag: '🇬🇳', phoneCode: '+224' },
  DNK: { name: 'Denmark', flag: '🇩🇰', phoneCode: '+45' },
  GLP: { name: 'Guadeloupe', flag: '🇬🇵', phoneCode: '+590' },
  GTM: { name: 'Guatemala', flag: '🇬🇹', phoneCode: '+502' },
  GNB: { name: 'Guinea-Bissau', flag: '🇬🇼', phoneCode: '+245' },
  GNQ: { name: 'Equatorial Guinea', flag: '🇬🇶', phoneCode: '+240' },
  PRK: { name: 'North Korea', flag: '🇰🇵', phoneCode: '+850' },
  GRD: { name: 'Grenada', flag: '🇬🇩', phoneCode: '+1473' },
  GRL: { name: 'Greenland', flag: '🇬🇱', phoneCode: '+299' },
  GUF: { name: 'French Guiana', flag: '🇬🇫', phoneCode: '+594' },
  GUY: { name: 'Guyana', flag: '🇬🇾', phoneCode: '+592' },
  EST: { name: 'Estonia', flag: '🇪🇪', phoneCode: '+372' },
  HKG: { name: 'Hong Kong', flag: '🇭🇰', phoneCode: '+852' },
  HMD: { name: 'Heard Island and McDonald Islands', flag: '🇭🇲', phoneCode: '+672' },
  FRA: { name: 'France', flag: '🇫🇷', phoneCode: '+33' },
  IND: { name: 'India', flag: '🇮🇳', phoneCode: '+91' },
  HND: { name: 'Honduras', flag: '🇭🇳', phoneCode: '+504' },
  NIC: { name: 'Nicaragua', flag: '🇳🇮', phoneCode: '+505' },
  HTI: { name: 'Haiti', flag: '🇭🇹', phoneCode: '+509' },
  DEU: { name: 'Germany', flag: '🇩🇪', phoneCode: '+49' },
  IDN: { name: 'Indonesia', flag: '🇮🇩', phoneCode: '+62' },
  GRC: { name: 'Greece', flag: '🇬🇷', phoneCode: '+30' },
  ISR: { name: 'Israel', flag: '🇮🇱', phoneCode: '+972' },
  JAM: { name: 'Jamaica', flag: '🇯🇲', phoneCode: '+1876' },
  JEY: { name: 'Jersey', flag: '🇯🇪', phoneCode: '+44' },
  JOR: { name: 'Jordan', flag: '🇯🇴', phoneCode: '+962' },
  JPN: { name: 'Japan', flag: '🇯🇵', phoneCode: '+81' },
  KAZ: { name: 'Kazakhstan', flag: '🇰🇿', phoneCode: '+7' },
  KEN: { name: 'Kenya', flag: '🇰🇪', phoneCode: '+254' },
  KGZ: { name: 'Kyrgyzstan', flag: '🇰🇬', phoneCode: '+996' },
  KIR: { name: 'Kiribati', flag: '🇰🇮', phoneCode: '+686' },
  HUN: { name: 'Hungary', flag: '🇭🇺', phoneCode: '+36' },
  ISL: { name: 'Iceland', flag: '🇮🇸', phoneCode: '+354' },
  LAO: { name: 'Laos', flag: '🇱🇦', phoneCode: '+856' },
  LBR: { name: 'Liberia', flag: '🇱🇷', phoneCode: '+231' },
  IRN: { name: 'Iran', flag: '🇮🇷', phoneCode: '+98' },
  IRQ: { name: 'Iraq', flag: '🇮🇶', phoneCode: '+964' },
  IRL: { name: 'Ireland', flag: '🇮🇪', phoneCode: '+353' },
  LIE: { name: 'Liechtenstein', flag: '🇱🇮', phoneCode: '+423' },
  LSO: { name: 'Lesotho', flag: '🇱🇸', phoneCode: '+266' },
  ITA: { name: 'Italy', flag: '🇮🇹', phoneCode: '+39' },
  MAC: { name: 'Macau', flag: '🇲🇴', phoneCode: '+853' },
  MCO: { name: 'Monaco', flag: '🇲🇨', phoneCode: '+377' },
  MDA: { name: 'Moldova', flag: '🇲🇩', phoneCode: '+373' },
  MDG: { name: 'Madagascar', flag: '🇲🇬', phoneCode: '+261' },
  MDV: { name: 'Maldives', flag: '🇲🇻', phoneCode: '+960' },
  MEX: { name: 'Mexico', flag: '🇲🇽', phoneCode: '+52' },
  MHL: { name: 'Marshall Islands', flag: '🇲🇭', phoneCode: '+692' },
  MKD: { name: 'North Macedonia', flag: '🇲🇰', phoneCode: '+389' },
  MNG: { name: 'Mongolia', flag: '🇲🇳', phoneCode: '+976' },
  LVA: { name: 'Latvia', flag: '🇱🇻', phoneCode: '+371' },
  LBN: { name: 'Lebanon', flag: '🇱🇧', phoneCode: '+961' },
  MRT: { name: 'Mauritania', flag: '🇲🇷', phoneCode: '+222' },
  MSR: { name: 'Montserrat', flag: '🇲🇸', phoneCode: '+1664' },
  LBY: { name: 'Libya', flag: '🇱🇾', phoneCode: '+218' },
  MTQ: { name: 'Martinique', flag: '🇲🇶', phoneCode: '+596' },
  LTU: { name: 'Lithuania', flag: '🇱🇹', phoneCode: '+370' },
  LUX: { name: 'Luxembourg', flag: '🇱🇺', phoneCode: '+352' },
  MUS: { name: 'Mauritius', flag: '🇲🇺', phoneCode: '+230' },
  MYS: { name: 'Malaysia', flag: '🇲🇾', phoneCode: '+60' },
  NPL: { name: 'Nepal', flag: '🇳🇵', phoneCode: '+977' },
  NAM: { name: 'Namibia', flag: '🇳🇦', phoneCode: '+264' },
  MLI: { name: 'Mali', flag: '🇲🇱', phoneCode: '+223' },
  MLT: { name: 'Malta', flag: '🇲🇹', phoneCode: '+356' },
  NER: { name: 'Niger', flag: '🇳🇪', phoneCode: '+227' },
  NRU: { name: 'Nauru', flag: '🇳🇷', phoneCode: '+674' },
  NZL: { name: 'New Zealand', flag: '🇳🇿', phoneCode: '+64' },
  PYF: { name: 'French Polynesia', flag: '🇵🇫', phoneCode: '+689' },
  SLV: { name: 'El Salvador', flag: '🇸🇻', phoneCode: '+503' },
  SWZ: { name: 'Eswatini', flag: '🇸🇿', phoneCode: '+268' },
  TCD: { name: 'Chad', flag: '🇹🇩', phoneCode: '+235' },
  MOZ: { name: 'Mozambique', flag: '🇲🇿', phoneCode: '+258' },
  MMR: { name: 'Myanmar', flag: '🇲🇲', phoneCode: '+95' },
  NLD: { name: 'Netherlands', flag: '🇳🇱', phoneCode: '+31' },
  AGO: { name: 'Angola', flag: '🇦🇴', phoneCode: '+244' },
  NOR: { name: 'Norway', flag: '🇳🇴', phoneCode: '+47' },
  PRY: { name: 'Paraguay', flag: '🇵🇾', phoneCode: '+595' },
  AFG: { name: 'Afghanistan', flag: '🇦🇫', phoneCode: '+93' },
  BGR: { name: 'Bulgaria', flag: '🇧🇬', phoneCode: '+359' },
  FIN: { name: 'Finland', flag: '🇫🇮', phoneCode: '+358' },
  GMB: { name: 'Gambia', flag: '🇬🇲', phoneCode: '+220' },
  PAK: { name: 'Pakistan', flag: '🇵🇰', phoneCode: '+92' },
  POL: { name: 'Poland', flag: '🇵🇱', phoneCode: '+48' },
  PRT: { name: 'Portugal', flag: '🇵🇹', phoneCode: '+351' },
  WSM: { name: 'Samoa', flag: '🇼🇸', phoneCode: '+685' },
  PSE: { name: 'Palestine', flag: '🇵🇸', phoneCode: '+970' },
  COG: { name: 'Congo', flag: '🇨🇬', phoneCode: '+242' },
  ROU: { name: 'Romania', flag: '🇷🇴', phoneCode: '+40' },
  RUS: { name: 'Russia', flag: '🇷🇺', phoneCode: '+7' },
  YEM: { name: 'Yemen', flag: '🇾🇪', phoneCode: '+967' },
  QAT: { name: 'Qatar', flag: '🇶🇦', phoneCode: '+974' },
  RWA: { name: 'Rwanda', flag: '🇷🇼', phoneCode: '+250' },
  ZAF: { name: 'South Africa', flag: '🇿🇦', phoneCode: '+27' },
  ZMB: { name: 'Zambia', flag: '🇿🇲', phoneCode: '+260' },
  SEN: { name: 'Senegal', flag: '🇸🇳', phoneCode: '+221' },
  UK: { name: 'United Kingdom', flag: '🇬🇧', phoneCode: '+44' },
  SVK: { name: 'Slovakia', flag: '🇸🇰', phoneCode: '+421' },
  SVN: { name: 'Slovenia', flag: '🇸🇮', phoneCode: '+386' },
  SOM: { name: 'Somalia', flag: '🇸🇴', phoneCode: '+252' },
  SSD: { name: 'South Sudan', flag: '🇸🇸', phoneCode: '+211' },
  ESP: { name: 'Spain', flag: '🇪🇸', phoneCode: '+34' },
  SAU: { name: 'Saudi Arabia', flag: '🇸🇦', phoneCode: '+966' },
  SDN: { name: 'Sudan', flag: '🇸🇩', phoneCode: '+249' },
  SWE: { name: 'Sweden', flag: '🇸🇪', phoneCode: '+46' },
  SGP: { name: 'Singapore', flag: '🇸🇬', phoneCode: '+65' },
  SYR: { name: 'Syria', flag: '🇸🇾', phoneCode: '+963' },
  TTO: { name: 'Trinidad and Tobago', flag: '🇹🇹', phoneCode: '+1868' },
  TUN: { name: 'Tunisia', flag: '🇹🇳', phoneCode: '+216' },
  UGA: { name: 'Uganda', flag: '🇺🇬', phoneCode: '+256' },
  SLB: { name: 'Solomon Islands', flag: '🇸🇧', phoneCode: '+677' },
  SLE: { name: 'Sierra Leone', flag: '🇸🇱', phoneCode: '+232' },
  SMR: { name: 'San Marino', flag: '🇸🇲', phoneCode: '+378' },
  SRB: { name: 'Serbia', flag: '🇷🇸', phoneCode: '+381' },
  STP: { name: 'São Tomé and Príncipe', flag: '🇸🇹', phoneCode: '+239' },
  VUT: { name: 'Vanuatu', flag: '🇻🇺', phoneCode: '+678' },
  ZWE: { name: 'Zimbabwe', flag: '🇿🇼', phoneCode: '+263' },
  ABW: { name: 'Aruba', flag: '🇦🇼', phoneCode: '+297' },
  AIA: { name: 'Anguilla', flag: '🇦🇮', phoneCode: '+1264' },
  BDI: { name: 'Burundi', flag: '🇧🇮', phoneCode: '+257' },
  BHR: { name: 'Bahrain', flag: '🇧🇭', phoneCode: '+973' },
  BMU: { name: 'Bermuda', flag: '🇧🇲', phoneCode: '+1441' },
  CHE: { name: 'Switzerland', flag: '🇨🇭', phoneCode: '+41' },
  CMR: { name: 'Cameroon', flag: '🇨🇲', phoneCode: '+237' },
  COD: { name: 'Democratic Republic of the Congo', flag: '🇨🇩', phoneCode: '+243' },
  COK: { name: 'Cook Islands', flag: '🇨🇰', phoneCode: '+682' },
  COL: { name: 'Colombia', flag: '🇨🇴', phoneCode: '+57' },
  COM: { name: 'Comoros', flag: '🇰🇲', phoneCode: '+269' },
  CPV: { name: 'Cape Verde', flag: '🇨🇻', phoneCode: '+238' },
  CRI: { name: 'Costa Rica', flag: '🇨🇷', phoneCode: '+506' },
  CUB: { name: 'Cuba', flag: '🇨🇺', phoneCode: '+53' },
  CUW: { name: 'Curaçao', flag: '🇨🇼', phoneCode: '+599' },
  CXR: { name: 'Christmas Island', flag: '🇨🇽', phoneCode: '+61' },
  CYM: { name: 'Cayman Islands', flag: '🇰🇾', phoneCode: '+1345' },
  DJI: { name: 'Djibouti', flag: '🇩🇯', phoneCode: '+253' },
  DMA: { name: 'Dominica', flag: '🇩🇲', phoneCode: '+1767' },
  DOM: { name: 'Dominican Republic', flag: '🇩🇴', phoneCode: '+1809' },
  DZA: { name: 'Algeria', flag: '🇩🇿', phoneCode: '+213' },
  FLK: { name: 'Falkland Islands', flag: '🇫🇰', phoneCode: '+500' },
  GAB: { name: 'Gabon', flag: '🇬🇦', phoneCode: '+241' },
  GIB: { name: 'Gibraltar', flag: '🇬🇮', phoneCode: '+350' },
  KNA: { name: 'Saint Kitts and Nevis', flag: '🇰🇳', phoneCode: '+1869' },
  KOR: { name: 'South Korea', flag: '🇰🇷', phoneCode: '+82' },
  KWT: { name: 'Kuwait', flag: '🇰🇼', phoneCode: '+965' },
  LCA: { name: 'Saint Lucia', flag: '🇱🇨', phoneCode: '+1758' },
  LKA: { name: 'Sri Lanka', flag: '🇱🇰', phoneCode: '+94' },
  MNE: { name: 'Montenegro', flag: '🇲🇪', phoneCode: '+382' },
  MWI: { name: 'Malawi', flag: '🇲🇼', phoneCode: '+265' },
  NGA: { name: 'Nigeria', flag: '🇳🇬', phoneCode: '+234' },
  OMN: { name: 'Oman', flag: '🇴🇲', phoneCode: '+968' },
  PAN: { name: 'Panama', flag: '🇵🇦', phoneCode: '+507' },
  PER: { name: 'Peru', flag: '🇵🇪', phoneCode: '+51' },
  PHL: { name: 'Philippines', flag: '🇵🇭', phoneCode: '+63' },
  PLW: { name: 'Palau', flag: '🇵🇼', phoneCode: '+680' },
  PNG: { name: 'Papua New Guinea', flag: '🇵🇬', phoneCode: '+675' },
  SUR: { name: 'Suriname', flag: '🇸🇷', phoneCode: '+597' },
  SYC: { name: 'Seychelles', flag: '🇸🇨', phoneCode: '+248' },
  TCA: { name: 'Turks and Caicos Islands', flag: '🇹🇨', phoneCode: '+1649' },
  TGO: { name: 'Togo', flag: '🇹🇬', phoneCode: '+228' },
  THA: { name: 'Thailand', flag: '🇹🇭', phoneCode: '+66' },
  TJK: { name: 'Tajikistan', flag: '🇹🇯', phoneCode: '+992' },
  TKM: { name: 'Turkmenistan', flag: '🇹🇲', phoneCode: '+993' },
  TLS: { name: 'Timor-Leste', flag: '🇹🇱', phoneCode: '+670' },
  TON: { name: 'Tonga', flag: '🇹🇴', phoneCode: '+676' },
  TUR: { name: 'Turkey', flag: '🇹🇷', phoneCode: '+90' },
  TUV: { name: 'Tuvalu', flag: '🇹🇻', phoneCode: '+688' },
  TWN: { name: 'Taiwan', flag: '🇹🇼', phoneCode: '+886' },
  TZA: { name: 'Tanzania', flag: '🇹🇿', phoneCode: '+255' },
  UAE: { name: 'United Arab Emirates', flag: '🇦🇪', phoneCode: '+971' },
  UKR: { name: 'Ukraine', flag: '🇺🇦', phoneCode: '+380' },
  URY: { name: 'Uruguay', flag: '🇺🇾', phoneCode: '+598' },
  USA: { name: 'United States', flag: '🇺🇸', phoneCode: '+1' },
  UZB: { name: 'Uzbekistan', flag: '🇺🇿', phoneCode: '+998' },
  VAT: { name: 'Vatican City', flag: '🇻🇦', phoneCode: '+39' },
  VCT: { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', phoneCode: '+1784' },
  VEN: { name: 'Venezuela', flag: '🇻🇪', phoneCode: '+58' },
  VIR: { name: 'United States Virgin Islands', flag: '🇻🇮', phoneCode: '+1340' },
  VNM: { name: 'Vietnam', flag: '🇻🇳', phoneCode: '+84' },
  GBR: { name: 'United Kingdom', flag: '🇬🇧', phoneCode: '+44' },
  // OTHER: { name: 'Other', flag: '🏴‍☠', phoneCode: '+0' },
}

export const countriesArray = Object.entries(countriesData)
  .map(([code, data]) => ({
    code,
    name: data.name,
    flag: data.flag,
    phoneCode: data.phoneCode,
  }))
  .sort((a, b) => parseInt(a.phoneCode) - parseInt(b.phoneCode))

export const countryOptions = Object.values(countriesData)
  .map(country => ({
    value: country.name,
    label: country.name,
  }))
  .sort((a, b) => a.label.localeCompare(b.label))

type MatchResult = {
  country: Country
  restNumber: string
} | null

export function getCountryByPhoneNumber(phone: string): MatchResult {
  if (!phone) return null
  const normalized = phone.replace(/[^\d+]/g, '') // удаляем пробелы, скобки и прочее
  const possibleCodes = Object.entries(countriesData)
    .map(([code, data]) => ({
      ...data,
      phoneCode: data.phoneCode.replace(/\D/g, ''), // убираем '+' если есть
    }))
    .sort((a, b) => b.phoneCode.length - a.phoneCode.length) // ищем самый длинный совпадающий код

  for (const country of possibleCodes) {
    if (normalized.startsWith(`+${country.phoneCode}`)) {
      return {
        country: {
          ...country,
          phoneCode: `+${country.phoneCode}`, // возвращаем с плюсом
        },
        restNumber: normalized.slice(country.phoneCode.length + 1),
      }
    }
  }

  return null
}
